name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  pages: write
  id-token: write

jobs:
  pre-checks:
    name: Run Tests and Linter
    uses: ./.github/workflows/tests-and-lint.yml

  release:
    name: Release
    needs: pre-checks
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22'

      - name: Install dependencies
        run: npm ci

      - name: Authenticate with NPM
        run: echo "//registry.npmjs.org/:_authToken=${{ secrets.NPM_TOKEN }}" > ~/.npmrc

      - name: Build NPM package
        run: npm run build

      - name: Publish NPM package
        shell: bash
        run: |
          npm version ${{ github.ref_name }} --no-git-tag-version
          npm publish --access public

      - name: Build storybook
        run: npm run build-storybook

      - name: Upload storybook
        uses: actions/upload-pages-artifact@v3
        with:
          path: storybook-static/

      - name: Deploy storybook to GitHub Pages
        uses: actions/deploy-pages@v4
        with:
          token: ${{ github.token }}
